version: '3.8'

services:
  
  api:
    build: .
    
    ports:
      - "8080:3000"
    
    depends_on:
      - postgresdb
    
    environment:
      
      DB_HOST: postgresdb 
    restart: always

  
  postgresdb:
    image: postgres:16-alpine 
    hostname: postgresdb
    
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendasdb
    
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: